services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/AgronomistStudio/node_modules
    command: npm run dev:api --workspace=server
