import { YieldPrediction, OptimizationResult, RiskAssessment, BenchmarkResult, ClusterInfo, FieldYieldHistory } from 'shared';

const DISCLAIMER =
  'This explanation is generated by the AI layer. ' +
  'All numeric values are computed by deterministic ML models trained on historical data — ' +
  'not estimated or invented by AI.';

const CROP_BASELINES: Record<string, number> = {
  almond: 4100,
  tomato: 84000,
  'processing tomatoes': 84000,
  pistachio: 2950,
  grape: 14000,
  alfalfa: 18000,
};

function hashCode(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = (Math.imul(31, h) + s.charCodeAt(i)) >>> 0;
  }
  return h;
}

export function computeMockYield(fieldId: string, cropName: string): YieldPrediction {
  const normCrop = cropName.toLowerCase().replace(/s$/, ''); // trim trailing 's' e.g. almonds -> almond
  const baseline = CROP_BASELINES[normCrop] ?? CROP_BASELINES[cropName.toLowerCase()] ?? 4100;
  const predicted = Math.round(baseline * (0.92 + (hashCode(fieldId) % 100) / 500));
  const interval = Math.round(predicted * 0.12);
  const water = 0.38;
  const nutrient = 0.29;

  return {
    field_id: fieldId,
    crop_name: cropName,
    crop_year: 2026,
    predicted_yield_kg_ha: predicted,
    yield_lower_kg_ha: predicted - interval,
    yield_upper_kg_ha: predicted + interval,
    baseline_yield_kg_ha: baseline,
    confidence: 'high',
    factor_water: water,
    factor_nutrient: nutrient,
    factor_heat: 0.15,
    factor_uv: 0.08,
    factor_seed: 0.06,
    factor_planting: 0.04,
    limiting_factors: ['water', 'nutrient'],
    explanation:
      `The model predicts ${predicted.toLocaleString()} kg/ha for ${cropName} — ` +
      `${((predicted - baseline) / baseline * 100).toFixed(1)}% ` +
      `${predicted >= baseline ? 'above' : 'below'} the ${baseline.toLocaleString()} kg/ha historical baseline. ` +
      `Water accounts for ${Math.round(water * 100)}% and nutrients ${Math.round(nutrient * 100)}% of sensitivity. ` +
      `Confidence is high based on available historical records.`,
    disclaimer: DISCLAIMER,
  };
}

export function computeMockOptimize(
  fieldId: string,
  irrigationIn?: number,
  nitrogenLbAc?: number
): OptimizationResult {
  const hash = hashCode(fieldId);
  const currentIrrigation = irrigationIn ?? (38 + (hash % 10));
  const currentNitrogen = nitrogenLbAc ?? (160 + (hash % 40));

  const recIrrigation = currentIrrigation + 4.5;
  const recNitrogen = currentNitrogen + 30.0;

  const baselineYield = 4120 + (hash % 300);
  const expectedYield = Math.round(baselineYield * 1.063);
  const expectedYieldGainPct = 6.3;

  return {
    field_id: fieldId,
    crop_year: 2026,
    current_irrigation_in: currentIrrigation,
    rec_irrigation_in: recIrrigation,
    irrigation_delta_in: 4.5,
    current_nitrogen_lb_ac: currentNitrogen,
    rec_nitrogen_lb_ac: recNitrogen,
    nitrogen_delta_lb_ac: 30.0,
    expected_yield_kg_ha: expectedYield,
    expected_yield_gain_pct: expectedYieldGainPct,
    baseline_yield_kg_ha: baselineYield,
    confidence: 'medium',
    explanation:
      `The optimizer recommends to increase irrigation by 4.5 in and apply 30 lb/ac more nitrogen. ` +
      `This is projected to improve yield by 6.3% (confidence: medium). ` +
      `Recommendations are derived from partial-dependence analysis over the trained yield model.`,
    disclaimer: DISCLAIMER,
  };
}

export function computeMockRiskSummary(): RiskAssessment[] {
  return [
    {
      field_id: 'field-001',
      crop_year: 2026,
      anomaly_score: 0.68,
      risk_label: 'high',
      residual_zscore: 2.1,
      top_risk_factors: ['season_irrigation_in', 'soil_ph', 'organic_matter_pct'],
      cohort_id: 0,
      cohort_name: 'High-input intensive',
      explanation:
        'Risk assessment: high (anomaly score 0.68). This field deviates 2.1 standard deviations ' +
        'from its peer cohort on: season irrigation, soil pH, organic matter. ' +
        'The Isolation Forest algorithm flagged these deviations based on patterns in the training dataset.',
      disclaimer: DISCLAIMER,
    },
    {
      field_id: 'field-002',
      crop_year: 2026,
      anomaly_score: 0.31,
      risk_label: 'low',
      residual_zscore: 0.8,
      top_risk_factors: ['nitrate_n_ppm', 'phosphorus_ppm'],
      cohort_id: 1,
      cohort_name: 'Mixed cohort 1',
      explanation:
        'Risk assessment: low (anomaly score 0.31). This field is within normal range of its peer cohort.',
      disclaimer: DISCLAIMER,
    },
    {
      field_id: 'field-003',
      crop_year: 2026,
      anomaly_score: 0.44,
      risk_label: 'moderate',
      residual_zscore: 1.3,
      top_risk_factors: ['potassium_ppm', 'season_n_applied'],
      cohort_id: 2,
      cohort_name: 'Low-input conservative',
      explanation:
        'Risk assessment: moderate (anomaly score 0.44). Nutrient levels deviate moderately from cohort median.',
      disclaimer: DISCLAIMER,
    },
  ];
}

export function computeMockBenchmark(fieldId: string): BenchmarkResult {
  const hash = hashCode(fieldId);
  const pct = 55 + (hash % 30);
  const clusterLabel = hash % 6;
  const clusterNames = [
    'High-input intensive',
    'Mixed cohort 1',
    'Low-input conservative',
    'Irrigation-intensive',
    'Nutrient-intensive',
    'Mixed cohort 5',
  ];
  const clusterName = clusterNames[clusterLabel] || 'Mixed cohort 1';

  return {
    field_id: fieldId,
    crop_year: 2026,
    cluster_label: clusterLabel,
    cluster_name: clusterName,
    yield_kg_ha: 4380 + (hash % 200),
    percentile_rank: pct,
    cohort_size: 47 + (hash % 10),
    explanation:
      `This field ranks at the ${pct}th percentile within its peer group: ` +
      `"${clusterName}" (${47 + (hash % 10)} comparable fields). ` +
      `Percentile ranking is based on k-means cohort assignment using agronomic input features.`,
    disclaimer: DISCLAIMER,
  };
}

export const MOCK_CLUSTERS: ClusterInfo[] = [
  { cluster_label: 0, cluster_name: 'High-input intensive' },
  { cluster_label: 1, cluster_name: 'Mixed cohort 1' },
  { cluster_label: 2, cluster_name: 'Low-input conservative' },
  { cluster_label: 3, cluster_name: 'Irrigation-intensive' },
  { cluster_label: 4, cluster_name: 'Nutrient-intensive' },
  { cluster_label: 5, cluster_name: 'Mixed cohort 5' },
];

export function computeMockFieldHistory(fieldId: string, cropName: string): FieldYieldHistory {
  const hash = hashCode(fieldId);
  const normCrop = cropName.toLowerCase().replace(/s$/, '');
  const baseline = CROP_BASELINES[normCrop] ?? CROP_BASELINES[cropName.toLowerCase()] ?? 4100;

  const history = [2022, 2023, 2024, 2025].map((year) => {
    const variance = 0.85 + ((hash + year) % 100) / 333; // ~0.85 to 1.15
    const yieldAmount = Math.round(baseline * variance);
    const irrigation = parseFloat((35 + ((hash + year) % 15) + (year % 3)).toFixed(1));
    const nitrogen = 140 + ((hash + year) % 60) + (year % 10);

    return {
      crop_year: year,
      yield_kg_ha: yieldAmount,
      irrigation_in: irrigation,
      nitrogen_applied_lb_ac: nitrogen,
    };
  });

  return {
    field_id: fieldId,
    crop_name: cropName,
    history,
  };
}
